### ISSUE TITLE
Save header and output in outmaf

### ISSUE THREAD

**Issue by kk988** [mskcc/facets-suite#12]
I need the output maf to keep the header information in the input maf.

**Comment by kk988** [comment]
Sorry, I should have been more specific. In mafAnno.R the header from the input maf is just ignored and not saved. I need the header information to be saved and included into the output maf. 

I hope this makes more sense!

**Comment by kpjonsson** [comment]
Added a fix, use argument `-c` and let me know if it works.

**Comment by kk988** [comment]
This is fixed now, thanks!
