### ISSUE TITLE
Plotting Issues

### ISSUE THREAD

**Issue by arichards2564** [mskcc/facets-suite#31]
I've run into several odd plots from facets-suite. The main issues seem to be the cf plots which seem like they might be stretched so that the plots are no longer aligned. I've also seen where the lines are not aligned with actual allele numbers (e.g. the segment should be 6,3 and the cncf plot shows more like 5.5,3). Lastly, the first log ratio plot seems to be plotting oddly. It seems to be setting the diplogR to 0 (even when the diplogR is < -1) and shifting the whole plot up. When you look at the segmentation text file, it seems OK.

**Comment by cband** [comment]
fixed both issues: with axes for ICN and CF.
