### ISSUE TITLE
Discarding High Amps

### ISSUE THREAD

**Issue by arichards2564** [mskcc/facets-suite#37]
I'm not sure if this is the correct place, but I think it is. It looks like any AMP with TCN > 8 is being termed "INDETERMINATE" because that TCN doesn't exist in the call table. There should be a line saying that if TCN > 8, then we call it an AMP.

https://github.com/mskcc/facets-suite/blob/f2b3a46ef00085fd56c693536f66992c691809be/R/gene-level-changes.R#L85

**Comment by cband** [comment]
fixed it. Added new copy number states in: https://github.com/mskcc/facets-suite/blob/master/data-raw/sysdata.R#L174.

@arichards2564 I did not make any changes to prior copy number states; only added those for LCN=NAs. I am closing this but do let me know if you see something.
